#+TITLE: README

[[https://www.packer.io/][Packer]] is a tool for virtual machine image and container management supporting creation and provisioning of multiple /boxes/.

This repository contains a collection of scripts to build a VirtualBox  OVF image, and a Vagrant Box that contains an installation of the latest *stable* release of [[https://www.idris-lang.org][Idris]].

The idea behind this /box provisioning/ is to provide fellow researchers with an image suitable for production of Research Artifacts suitable for evaluation.
While we, as Scientists, often publish papers and code online, these artifacts are more tuned towards reproducible results and conservancy of the research as it was done at the time.

The box is intended to allow evaluators access to a working Idris compiler, and evaluate artifacts using the command line.

Soon, I will publish example packer scripts demonstrating how we can use this base virtual box image to create actual research artifacts.

While we could use Docker, Packer is a Swiss Army knife of tooling that supports generation of many kinds of images.

This vagrant box has not been tested with vagrant.


** Details

| Base OS | Ubuntu Server 18.04.02 LTS |
| CPU     |                     64-AMD |
| Memory  |                       4 GB |
| Disk    |                      20 GB |
| Cores   |                          2 |
| GHC     |                      8.2.2 |
| Cabal   |                        2.0 |
| Idris   |                      1.3.1 |

* PreInstalled Software

The box provisioned is Ubuntu 18.04.02 Server.

Extra software was installed to support Idris installation.

Other notable installed software include:

+ mg :: A lightweight emacs clone.
