name: Build

on:
  push:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y packer virtualbox virtualbox-guest-additions-iso
      - name: Build alpine VM
        run: HEADLESS=true make alpine
      - name: Build idris VM
        run: make idris
      - name: Test example
        run: cd example && make
